"use client";

import React, { useState, useEffect } from "react";
import posthog from "posthog-js";
import Link from "next/link";
import Image from "next/image";
import {
  Shield,
  ShieldCheck,
  Play,
  Pause,
  RotateCcw,
  Circle,
  FileCode,
  Terminal,
  Database,
  Download,
  Lock,
  Check,
  X,
  ArrowRight,
  Code2,
  CheckCircle2,
  ChevronRight,
  Key,
  Copy,
  Cpu,
  ServerOff,
  Layers,
  Sparkles,
  FileSpreadsheet,
  ExternalLink,
  Table,
  Upload,
  Zap,
} from "lucide-react";

const CHROME_STORE_URL =
  "https://chromewebstore.google.com/detail/flowmacro-%E2%80%94-web-automatio/agehjimobcongfgkagfjhmlibkkmjppc?hl=en-US&utm_source=ext_sidebar";

// Mock Steps for Hero Dual-Pane IDE Terminal
const HERO_COMMANDS = [
  {
    id: 1,
    command: "open",
    target: "https://app.supabase.com/login",
    value: "-",
    status: "200 OK",
    type: "nav",
  },
  {
    id: 2,
    command: "type",
    target: 'css=[data-testid="email-input"]',
    value: "lead.engineer@acme.dev",
    status: "Resolved",
    type: "input",
  },
  {
    id: 3,
    command: "type",
    target: "id=password",
    value: "{{SECRET_PASSWORD}}",
    status: "AES-256 Protected",
    isSensitive: true,
    type: "secret",
  },
  {
    id: 4,
    command: "click",
    target: "button#login-submit",
    status: "Executed",
    type: "click",
  },
  {
    id: 5,
    command: "waitFor",
    target: '#prod-analytics-cluster',
    value: "visible",
    status: "Verified",
    type: "assert",
  },
];

export default function LandingPage() {
  // Terminal Replay Simulation State
  const [activeStepIndex, setActiveStepIndex] = useState(0);
  const [isReplaying, setIsReplaying] = useState(true);
  const [logs, setLogs] = useState<string[]>([
    "[14:02:11.104] [INFO] Target window #1024 attached via chrome.debugger protocol",
    "[14:02:11.240] [OK] Navigated to https://app.supabase.com/login (200 OK, 124ms)",
    "[14:02:11.750] [DOM] Resolved selector 'input#email' in 3.4ms",
    "[14:02:12.180] [SHIELD] 🛡️ Sensitive input detected: value masked with {{SECRET_PASSWORD}}. AES-256 encrypted in RAM.",
    "[14:02:12.620] [ACTION] Dispatching trusted click event to button#login-submit",
    "[14:02:13.110] [SUCCESS] Replay executed on tab #1024 in 1.87s with 0 errors.",
  ]);

  // Tabbed Exporter Demo State
  const [activeExporter, setActiveExporter] = useState<"playwright" | "puppeteer" | "selenium" | "json">("playwright");
  const [copiedCode, setCopiedCode] = useState(false);

  // Auto step runner for hero dual-pane mockup
  useEffect(() => {
    if (!isReplaying) return;
    const interval = setInterval(() => {
      setActiveStepIndex((prev) => {
        const next = (prev + 1) % HERO_COMMANDS.length;
        const current = HERO_COMMANDS[next];
        const time = new Date().toLocaleTimeString();

        let newLog = `[${time}] [CMD] #${current.id} ${current.command} -> ${current.target}`;
        if (current.isSensitive) {
          newLog = `[${time}] [VAULT] 🛡️ Password auto-masked as {{SECRET_PASSWORD}}. WebCrypto AES-256-GCM armed. 0 bytes leaked.`;
        } else if (current.id === 5) {
          newLog = `[${time}] [SUCCESS] Replay executed on tab #1024 with 0 DOM errors.`;
        }

        setLogs((prevLogs) => [...prevLogs.slice(-5), newLog]);
        return next;
      });
    }, 1800);

    return () => clearInterval(interval);
  }, [isReplaying]);

  const handleCopyCode = (code: string) => {
    navigator.clipboard.writeText(code);
    setCopiedCode(true);
    setTimeout(() => setCopiedCode(false), 2000);
  };

  const getExporterSnippet = () => {
    switch (activeExporter) {
      case "playwright":
        return `// Generated by FlowMacro IDE • Playwright (TypeScript)
import { test, expect } from '@playwright/test';

test('Automated Supabase Login Workflow', async ({ page }) => {
  // 🛡️ Zero-Trust Vault: Credentials loaded strictly via environment
  // Plain-text password is NEVER committed to repository or CI logs
  const AUTO_MACRO_PASSWORD = process.env.AUTO_MACRO_PASSWORD || '';

  await page.goto('https://app.supabase.com/login');
  await page.locator('css=[data-testid="email-input"]').fill('lead.engineer@acme.dev');

  // Injected securely into DOM without plain-text leakage
  await page.locator('input[type="password"]').fill(AUTO_MACRO_PASSWORD);
  await page.locator('button#login-submit').click();

  await expect(page.locator('#prod-analytics-cluster')).toBeVisible();
});`;

      case "puppeteer":
        return `// Generated by FlowMacro IDE • Puppeteer (JavaScript)
const puppeteer = require('puppeteer');

(async () => {
  // 🛡️ Zero-Trust Secret: Masked runtime environment variable
  const AUTO_MACRO_PASSWORD = process.env.AUTO_MACRO_PASSWORD || '';

  const browser = await puppeteer.launch({ headless: false });
  const page = await browser.newPage();

  await page.goto('https://app.supabase.com/login');
  await page.type('[data-testid="email-input"]', 'lead.engineer@acme.dev');

  // Sensitive field populated securely
  await page.type('input[type="password"]', AUTO_MACRO_PASSWORD);
  await page.click('button#login-submit');

  await page.waitForSelector('#prod-analytics-cluster');
  await browser.close();
})();`;

      case "selenium":
        return `# Generated by FlowMacro IDE • Python Selenium
import os
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC

# 🛡️ Zero-Trust Secret: Loaded securely via OS environment variable
AUTO_MACRO_PASSWORD = os.getenv('AUTO_MACRO_PASSWORD', '')

driver = webdriver.Chrome()
driver.get("https://app.supabase.com/login")

email_elem = driver.find_element(By.CSS_SELECTOR, '[data-testid="email-input"]')
email_elem.send_keys("lead.engineer@acme.dev")

# Injected at runtime without plain-text hardcoding
pass_elem = driver.find_element(By.ID, "password")
pass_elem.send_keys(AUTO_MACRO_PASSWORD)

driver.find_element(By.ID, "login-submit").click()
WebDriverWait(driver, 10).until(
    EC.visibility_of_element_located((By.ID, "prod-analytics-cluster"))
)`;

      case "json":
        return `{
  "id": "macro-suite-1024",
  "version": "2.0",
  "name": "Supabase Production Flow",
  "url": "https://app.supabase.com",
  "tests": [{
    "id": "test-auth-run",
    "name": "Zero-Trust Login",
    "commands": [
      { "command": "open", "target": "https://app.supabase.com/login", "value": "" },
      { "command": "type", "target": "css=[data-testid='email-input']", "value": "lead.engineer@acme.dev" },
      {
        "command": "type",
        "target": "id=password",
        "value": "{{SECRET_PASSWORD}}",
        "isSensitive": true,
        "encryptedSecret": "ENC:AES256GCM:96bitNonce:b64..."
      },
      { "command": "click", "target": "button#login-submit", "value": "" },
      { "command": "waitFor", "target": "#prod-analytics-cluster", "value": "visible" }
    ]
  }]
}`;
    }
  };

  return (
    <div className="min-h-screen bg-[#0b0f17] text-slate-200 font-sans selection:bg-emerald-500/20 selection:text-emerald-300 antialiased bg-blueprint-matrix">
      {/* 1. NAVBAR */}
      <header className="sticky top-0 z-50 border-b border-slate-800/80 bg-[#0b0f17]/90 backdrop-blur-md">
        <div className="max-w-7xl mx-auto px-6 h-16 flex items-center justify-between">
          <div className="flex items-center gap-3">
            <Link href="/" className="flex items-center gap-2.5">
              <div className="w-8 h-8 rounded-lg overflow-hidden border border-emerald-500/30 bg-slate-900 shadow-sm flex items-center justify-center">
                <Image
                  src="/flowmacro_store_icon_128x128.png"
                  alt="FlowMacro IDE Logo"
                  width={32}
                  height={32}
                  className="w-full h-full object-cover"
                />
              </div>
              <div className="flex items-center gap-2">
                <span className="text-sm font-bold tracking-tight text-white font-mono">
                  FlowMacro <span className="text-emerald-400">IDE</span>
                </span>
                <span className="text-[10px] font-mono px-1.5 py-0.5 rounded bg-slate-900 text-slate-400 border border-slate-800">
                  v1.0.1
                </span>
              </div>
            </Link>
          </div>

          <nav className="hidden md:flex items-center gap-7 text-xs font-mono text-slate-400">
            <a href="#features" className="hover:text-emerald-400 transition-colors">
              Features
            </a>
            <a href="#vault" className="hover:text-emerald-400 transition-colors flex items-center gap-1">
              <Lock className="w-3 h-3 text-emerald-400" />
              Security Vault
            </a>
            <a href="#demo" className="hover:text-emerald-400 transition-colors">
              Exporters
            </a>
            <a href="#pricing" className="hover:text-emerald-400 transition-colors">
              Pricing
            </a>
            <Link href="/privacy" className="hover:text-emerald-400 transition-colors">
              Docs &amp; Privacy
            </Link>
          </nav>

          <div className="flex items-center gap-3">
            <a
              href={CHROME_STORE_URL}
              target="_blank"
              rel="noopener noreferrer"
              onClick={() => posthog.capture('clicked_install_chrome_store')}
              className="px-4 py-2 rounded-md bg-emerald-500 hover:bg-emerald-400 text-slate-950 text-xs font-mono font-bold transition-all shadow-[0_0_20px_rgba(16,185,129,0.2)] active:scale-95 flex items-center gap-1.5"
            >
              <span>Add to Chrome</span>
              <ArrowRight className="w-3.5 h-3.5" />
            </a>
          </div>
        </div>
      </header>

      {/* 2. HERO SECTION (Terminal & Replay Engine View) */}
      <section className="relative pt-20 pb-20 px-6 overflow-hidden bg-blueprint-radial">
        {/* Subtle emerald focal bloom */}
        <div className="absolute top-1/4 left-1/2 -translate-x-1/2 w-[650px] h-[300px] bg-emerald-500/10 blur-[120px] pointer-events-none rounded-full" />

        <div className="max-w-6xl mx-auto relative z-10 text-center">
          {/* Badge */}
          <div className="inline-flex items-center gap-2 font-mono text-xs text-emerald-400 border border-emerald-500/30 bg-emerald-500/10 px-3.5 py-1 rounded-full mb-8 shadow-sm">
            <span className="w-2 h-2 rounded-full bg-emerald-400 animate-ping" />
            <span>🛡️ Zero-Trust Web Automation &amp; Selenium IDE Engine</span>
          </div>

          {/* Headline */}
          <h1 className="text-4xl sm:text-6xl font-extrabold tracking-tight text-white mb-6 leading-[1.12] max-w-4xl mx-auto">
            Record Web Actions. <br />
            <span className="text-transparent bg-clip-text bg-gradient-to-r from-emerald-400 via-teal-300 to-mint-400">
              Mask Passwords.
            </span>{" "}
            Replay &amp; Export in Seconds.
          </h1>

          {/* Subheadline */}
          <p className="text-base sm:text-lg text-slate-400 max-w-3xl mx-auto mb-10 leading-relaxed font-normal">
            The developer-first Chrome extension that turns browser workflows into executable macros
            and clean Playwright, Puppeteer, or Python Selenium scripts with{" "}
            <span className="text-emerald-400 font-semibold font-mono">zero password leakage</span>.
          </p>

          {/* Primary CTAs */}
          <div className="flex flex-col sm:flex-row items-center justify-center gap-4 mb-16">
            <a
              href={CHROME_STORE_URL}
              target="_blank"
              rel="noopener noreferrer"
              onClick={() => posthog.capture('clicked_install_chrome_store')}
              className="w-full sm:w-auto px-6 py-3 rounded-lg bg-emerald-500 hover:bg-emerald-400 text-slate-950 text-xs font-mono font-bold transition-all shadow-[0_0_25px_rgba(16,185,129,0.3)] active:scale-95 flex items-center justify-center gap-2"
            >
              <span>Add to Chrome — Free</span>
              <ArrowRight className="w-4 h-4" />
            </a>
            <a
              href="#demo"
              onClick={() => posthog.capture('clicked_view_demo')}
              className="w-full sm:w-auto px-6 py-3 rounded-lg bg-[#0f172a] hover:bg-slate-800 text-slate-200 border border-slate-800 text-xs font-mono font-medium transition-all flex items-center justify-center gap-2"
            >
              <Terminal className="w-4 h-4 text-emerald-400" />
              <span>View Live Demo</span>
            </a>
          </div>

          {/* HERO MOCKUP: DUAL-PANE IDE TERMINAL */}
          <div className="rounded-xl border border-slate-800/80 bg-[#0f172a] shadow-2xl overflow-hidden text-left">
            {/* Window Top Bar */}
            <div className="h-10 px-4 bg-[#0b0f17] border-b border-slate-800 flex items-center justify-between">
              <div className="flex items-center gap-2">
                <div className="w-2.5 h-2.5 rounded-full bg-slate-700" />
                <div className="w-2.5 h-2.5 rounded-full bg-slate-700" />
                <div className="w-2.5 h-2.5 rounded-full bg-slate-700" />
                <span className="ml-3 text-xs font-mono text-slate-400 flex items-center gap-1.5">
                  <Terminal className="w-3.5 h-3.5 text-emerald-400" />
                  FlowMacro IDE • Standalone Controller (960 × 750px)
                </span>
              </div>

              <div className="flex items-center gap-2 font-mono text-[10px]">
                <span className="text-emerald-400 bg-emerald-500/10 border border-emerald-500/20 px-2 py-0.5 rounded flex items-center gap-1">
                  <span className="w-1.5 h-1.5 rounded-full bg-emerald-400 animate-pulse" />
                  TAB #1024 ATTACHED
                </span>
              </div>
            </div>

            {/* IDE Controls Toolbar */}
            <div className="px-4 py-2.5 bg-[#0b0f17]/60 border-b border-slate-800 flex flex-wrap items-center justify-between gap-3 text-xs font-mono">
              <div className="flex items-center gap-2 flex-1 max-w-md">
                <span className="text-slate-500 text-[11px]">BASE_URL:</span>
                <input
                  readOnly
                  value="https://app.supabase.com/login"
                  className="w-full px-2.5 py-1 bg-[#0b0f17] border border-slate-800 rounded font-mono text-xs text-slate-300 outline-none"
                />
              </div>

              <div className="flex items-center gap-2">
                <button
                  onClick={() => {
                    if (!isReplaying) posthog.capture('clicked_view_demo');
                    setIsReplaying(!isReplaying);
                  }}
                  className={`px-3 py-1 rounded text-xs font-semibold flex items-center gap-1.5 transition-all ${
                    isReplaying
                      ? "bg-amber-500/20 text-amber-300 border border-amber-500/40"
                      : "bg-emerald-500 hover:bg-emerald-400 text-slate-950 shadow-sm"
                  }`}
                >
                  {isReplaying ? (
                    <>
                      <Pause className="w-3 h-3 fill-amber-300" />
                      <span>Running (1x)...</span>
                    </>
                  ) : (
                    <>
                      <Play className="w-3 h-3 fill-slate-950" />
                      <span>Replay Macro</span>
                    </>
                  )}
                </button>

                <button
                  onClick={() => {
                    setActiveStepIndex(0);
                    setIsReplaying(false);
                    setLogs((prev) => [
                      ...prev,
                      `[${new Date().toLocaleTimeString()}] Reset playback head to step #1`,
                    ]);
                  }}
                  className="p-1 rounded bg-[#0b0f17] hover:bg-slate-800 text-slate-400 border border-slate-800 transition-colors"
                  title="Reset Replay"
                >
                  <RotateCcw className="w-3.5 h-3.5" />
                </button>

                <span className="flex items-center gap-1 px-2.5 py-1 rounded bg-rose-500/10 text-rose-400 border border-rose-500/20 text-[11px]">
                  <Circle className="w-2 h-2 fill-rose-500 animate-pulse" />
                  REC
                </span>
              </div>
            </div>

            {/* DUAL PANE CONTAINER */}
            <div className="grid grid-cols-1 lg:grid-cols-12 divide-y lg:divide-y-0 lg:divide-x divide-slate-800">
              {/* LEFT PANE: COMMAND TABLE */}
              <div className="lg:col-span-7 flex flex-col justify-between">
                <div className="divide-y divide-slate-800/80 font-mono text-xs">
                  <div className="grid grid-cols-12 gap-2 px-4 py-2 bg-[#0b0f17]/80 text-[10px] text-slate-500 uppercase font-semibold tracking-wider">
                    <div className="col-span-1">#</div>
                    <div className="col-span-2">Command</div>
                    <div className="col-span-5">Target Selector</div>
                    <div className="col-span-4">Value</div>
                  </div>

                  {HERO_COMMANDS.map((step, idx) => {
                    const isActive = activeStepIndex === idx;
                    return (
                      <div
                        key={step.id}
                        onClick={() => setActiveStepIndex(idx)}
                        className={`grid grid-cols-12 gap-2 px-4 py-2.5 items-center cursor-pointer transition-colors ${
                          isActive
                            ? "bg-slate-800/60 text-white border-l-2 border-emerald-400"
                            : "hover:bg-slate-800/30 text-slate-300"
                        }`}
                      >
                        <div className="col-span-1 text-slate-500 flex items-center gap-1">
                          {isActive ? (
                            <ChevronRight className="w-3 h-3 text-emerald-400" />
                          ) : (
                            <span>{step.id}</span>
                          )}
                        </div>

                        <div className="col-span-2">
                          <span className="px-1.5 py-0.5 rounded bg-[#0b0f17] border border-slate-800 text-[11px] text-emerald-400">
                            {step.command}
                          </span>
                        </div>

                        <div className="col-span-5 truncate text-slate-300 font-mono">
                          {step.target}
                        </div>

                        <div className="col-span-4 truncate">
                          {step.isSensitive ? (
                            <span className="inline-flex items-center gap-1 text-emerald-300 bg-emerald-500/10 border border-emerald-500/30 px-2 py-0.5 rounded text-[10px] font-bold">
                              <Lock className="w-2.5 h-2.5 text-emerald-400" />
                              &#123;&#123;SECRET_PASSWORD&#125;&#125;
                            </span>
                          ) : (
                            <span className="text-slate-400">{step.value}</span>
                          )}
                        </div>
                      </div>
                    );
                  })}
                </div>

                <div className="px-4 py-2.5 bg-[#0b0f17] border-t border-slate-800 text-[11px] font-mono text-slate-500 flex items-center justify-between">
                  <span>Deterministic Multi-Locator Waterfall</span>
                  <span className="text-emerald-400">5 / 5 Commands Ready</span>
                </div>
              </div>

              {/* RIGHT PANE: LIVE EXECUTION LOG TERMINAL (WARP AESTHETIC) */}
              <div className="lg:col-span-5 bg-[#090d14] flex flex-col justify-between">
                <div>
                  <div className="px-4 py-2 bg-[#0b0f17] border-b border-slate-800 flex items-center justify-between text-[10px] font-mono text-slate-500">
                    <span className="flex items-center gap-1.5 text-slate-400">
                      <Terminal className="w-3 h-3 text-emerald-400" />
                      LIVE EXECUTION LOGS
                    </span>
                    <span className="text-emerald-400 font-semibold">[STREAMING]</span>
                  </div>

                  <div className="p-4 space-y-2 text-[11px] font-mono">
                    {logs.map((log, idx) => (
                      <div
                        key={idx}
                        className={`leading-relaxed ${
                          log.includes("[SUCCESS]")
                            ? "text-emerald-400 font-semibold"
                            : log.includes("[SHIELD]") || log.includes("[VAULT]")
                            ? "text-mint-300 text-teal-300 font-medium"
                            : log.includes("[OK]")
                            ? "text-slate-200"
                            : "text-slate-400"
                        }`}
                      >
                        {log}
                      </div>
                    ))}
                    <div className="flex items-center gap-1 text-emerald-400 pt-2">
                      <span className="text-slate-500">&gt;</span>
                      <span className="w-2 h-3.5 bg-emerald-400 animate-cursor" />
                    </div>
                  </div>
                </div>

                <div className="px-4 py-2.5 bg-[#0b0f17] border-t border-slate-800 text-[11px] font-mono text-slate-400 flex items-center justify-between">
                  <span className="text-emerald-400 font-bold">[SUCCESS] Replay executed on tab #1024</span>
                  <span className="text-slate-500">0 Leaks</span>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* 3. FEATURE GRID (4 BLUEPRINT CARDS) */}
      <section id="features" className="py-24 px-6 border-t border-slate-800/80 bg-[#0b0f17]">
        <div className="max-w-6xl mx-auto">
          <div className="max-w-2xl mb-16">
            <span className="text-xs font-mono text-emerald-400 uppercase tracking-wider block mb-2">
              System Specification
            </span>
            <h2 className="text-3xl font-extrabold text-white tracking-tight mb-3">
              Four Core Architectural Pillars
            </h2>
            <p className="text-sm text-slate-400 leading-relaxed font-normal">
              Built for automation engineers, QA specialists, and developers who require deterministic browser replay and zero-trust security.
            </p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            {/* Card 1 */}
            <div className="p-6 rounded-xl bg-[#0f172a] border border-slate-800/80 hover:border-emerald-500/40 transition-colors flex flex-col justify-between">
              <div>
                <div className="w-10 h-10 rounded-lg bg-emerald-500/10 border border-emerald-500/20 flex items-center justify-center text-emerald-400 mb-4">
                  <Layers className="w-5 h-5" />
                </div>
                <h3 className="text-lg font-bold text-white mb-2 font-mono">
                  Selenium IDE Architecture
                </h3>
                <p className="text-xs text-slate-400 leading-relaxed">
                  Standalone popup controller window (960 × 750px) orchestrates target browser tabs via the Chrome Debugger
                  and Runtime protocol. Deterministic replay without in-page iframe collisions or DOM CSS pollution.
                </p>
              </div>
              <div className="mt-6 pt-4 border-t border-slate-800 text-[11px] font-mono text-emerald-400 flex items-center gap-1">
                <span>01 / DEDICATED CONTROLLER WINDOW</span>
              </div>
            </div>

            {/* Card 2 */}
            <div id="vault" className="p-6 rounded-xl bg-[#0f172a] border border-emerald-500/30 hover:border-emerald-500/50 transition-colors flex flex-col justify-between shadow-[0_0_30px_rgba(16,185,129,0.04)]">
              <div>
                <div className="w-10 h-10 rounded-lg bg-emerald-500/15 border border-emerald-500/30 flex items-center justify-center text-emerald-400 mb-4">
                  <ShieldCheck className="w-5 h-5" />
                </div>
                <h3 className="text-lg font-bold text-white mb-2 font-mono">
                  AES-256 Secret Vault
                </h3>
                <p className="text-xs text-slate-400 leading-relaxed">
                  Auto-detects <code className="text-slate-200">input[type=&quot;password&quot;]</code> and{" "}
                  <code className="text-slate-200">autocomplete=&quot;current-password&quot;</code>. Raw secrets are encrypted
                  locally via native Web Crypto API (AES-256-GCM) with 96-bit random IVs, exporting clean <code className="text-emerald-400">process.env</code> variables.
                </p>
              </div>
              <div className="mt-6 pt-4 border-t border-slate-800 text-[11px] font-mono text-emerald-400 flex items-center gap-1">
                <span>02 / ZERO-LEAK LOCAL ENCRYPTION</span>
              </div>
            </div>

            {/* Card 3 */}
            <div className="p-6 rounded-xl bg-[#0f172a] border border-slate-800/80 hover:border-emerald-500/40 transition-colors flex flex-col justify-between">
              <div>
                <div className="w-10 h-10 rounded-lg bg-teal-500/10 border border-teal-500/20 flex items-center justify-center text-teal-400 mb-4">
                  <FileSpreadsheet className="w-5 h-5" />
                </div>
                <h3 className="text-lg font-bold text-white mb-2 font-mono">
                  CSV Batch Execution Engine
                </h3>
                <p className="text-xs text-slate-400 leading-relaxed">
                  Upload any spreadsheet (<code className="text-slate-200">.csv</code>) to bind parameter columns like{" "}
                  <code className="text-slate-200">&#123;&#123;email&#125;&#125;</code> and{" "}
                  <code className="text-slate-200">&#123;&#123;user_id&#125;&#125;</code>. Execute multi-row form fills
                  and automated database migrations in seconds with throttled playback.
                </p>
              </div>
              <div className="mt-6 pt-4 border-t border-slate-800 text-[11px] font-mono text-teal-400 flex items-center gap-1">
                <span>03 / MASS DATA ENTRY RUNNER</span>
              </div>
            </div>

            {/* Card 4 */}
            <div className="p-6 rounded-xl bg-[#0f172a] border border-slate-800/80 hover:border-emerald-500/40 transition-colors flex flex-col justify-between">
              <div>
                <div className="w-10 h-10 rounded-lg bg-emerald-500/10 border border-emerald-500/20 flex items-center justify-center text-emerald-400 mb-4">
                  <FileCode className="w-5 h-5" />
                </div>
                <h3 className="text-lg font-bold text-white mb-2 font-mono">
                  Multi-Format Code Exporters
                </h3>
                <p className="text-xs text-slate-400 leading-relaxed">
                  1-click export to clean, idiomatic Playwright (TypeScript/JavaScript), Puppeteer, Python Selenium, or native
                  Selenium <code className="text-slate-200">.side</code> JSON files. Formatted with robust locator waterfalls and zero setup friction.
                </p>
              </div>
              <div className="mt-6 pt-4 border-t border-slate-800 text-[11px] font-mono text-emerald-400 flex items-center gap-1">
                <span>04 / PLAYWRIGHT • PUPPETEER • PYTHON</span>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* 4. TABBED CODE EXPORTER DEMO */}
      <section id="demo" className="py-24 px-6 border-t border-slate-800/80 bg-[#090d14]">
        <div className="max-w-5xl mx-auto">
          <div className="max-w-2xl mb-12">
            <span className="text-xs font-mono text-emerald-400 uppercase tracking-wider block mb-2">
              Code Generation Sandbox
            </span>
            <h2 className="text-3xl font-extrabold text-white tracking-tight mb-3">
              Clean, Zero-Leak Code Exporters
            </h2>
            <p className="text-sm text-slate-400 leading-relaxed">
              Observe how sensitive password inputs automatically render as <code className="text-emerald-400">process.env.AUTO_MACRO_PASSWORD</code> across all target frameworks.
            </p>
          </div>

          <div className="rounded-xl border border-slate-800 bg-[#0f172a] overflow-hidden shadow-2xl">
            {/* Tabs Bar */}
            <div className="px-4 py-3 bg-[#0b0f17] border-b border-slate-800 flex flex-wrap items-center justify-between gap-3">
              <div className="flex items-center gap-2">
                <span className="text-xs font-mono text-slate-500 mr-2 flex items-center gap-1">
                  <Code2 className="w-3.5 h-3.5 text-emerald-400" />
                  Target Framework:
                </span>
                {(["playwright", "puppeteer", "selenium", "json"] as const).map((framework) => (
                  <button
                    key={framework}
                    onClick={() => setActiveExporter(framework)}
                    className={`text-xs font-mono px-3 py-1.5 rounded transition-all ${
                      activeExporter === framework
                        ? "bg-emerald-500 text-slate-950 font-bold shadow-sm"
                        : "bg-[#0f172a] text-slate-400 hover:text-white border border-slate-800"
                    }`}
                  >
                    {framework === "playwright"
                      ? "Playwright (TS)"
                      : framework === "puppeteer"
                      ? "Puppeteer (JS)"
                      : framework === "selenium"
                      ? "Python Selenium"
                      : "JSON (.side)"}
                  </button>
                ))}
              </div>

              <button
                onClick={() => handleCopyCode(getExporterSnippet())}
                className="flex items-center gap-1.5 px-3 py-1.5 rounded bg-slate-800 hover:bg-slate-700 text-slate-200 text-xs font-mono border border-slate-700 transition-colors"
              >
                {copiedCode ? (
                  <>
                    <Check className="w-3.5 h-3.5 text-emerald-400" />
                    <span>Copied Code!</span>
                  </>
                ) : (
                  <>
                    <Copy className="w-3.5 h-3.5" />
                    <span>Copy Script</span>
                  </>
                )}
              </button>
            </div>

            {/* Code Content */}
            <div className="p-6 bg-[#0b0f17]/90 overflow-x-auto">
              <pre className="font-mono text-xs text-slate-300 leading-relaxed">
                <code>{getExporterSnippet()}</code>
              </pre>
            </div>
          </div>

          {/* Security Callout */}
          <div className="mt-6 flex items-center justify-between p-4 rounded-lg bg-[#0f172a] border border-slate-800 text-xs font-mono text-slate-400">
            <span className="flex items-center gap-2 text-slate-300">
              <ShieldCheck className="w-4 h-4 text-emerald-400" />
              <span>Tested &amp; Verified: 0 plain-text password leaks in generated code exports.</span>
            </span>
            <span className="text-emerald-400">PASSED (100% SECURE)</span>
          </div>
        </div>
      </section>

      {/* 5. PRICING SECTION (DODO PAYMENTS READY) */}
      <section id="pricing" className="py-24 px-6 border-t border-slate-800/80 bg-[#0b0f17]">
        <div className="max-w-4xl mx-auto">
          <div className="text-center max-w-xl mx-auto mb-16">
            <span className="text-xs font-mono text-emerald-400 uppercase tracking-wider block mb-2">
              Transparent Pricing
            </span>
            <h2 className="text-3xl font-extrabold text-white tracking-tight mb-2">
              Pay Once. Automate Forever.
            </h2>
            <p className="text-xs font-mono text-slate-400">
              Zero recurring subscriptions. Instant checkout powered by Dodo Payments.
            </p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
            {/* Free Tier */}
            <div className="p-7 rounded-xl bg-[#0f172a] border border-slate-800 flex flex-col justify-between">
              <div>
                <div className="flex items-center justify-between mb-2">
                  <span className="text-xs font-mono text-slate-400 uppercase">Community Edition</span>
                  <span className="text-xs font-mono text-slate-500">100% Free</span>
                </div>
                <div className="text-4xl font-extrabold text-white mb-4 font-mono">$0</div>
                <p className="text-xs text-slate-400 mb-6 leading-relaxed">
                  For individual developers recording and replaying local macros in browser tabs.
                </p>

                <ul className="space-y-3 text-xs font-mono text-slate-300 mb-8">
                  <li className="flex items-center gap-2">
                    <Check className="w-3.5 h-3.5 text-emerald-400" />
                    <span>Unlimited macro recordings</span>
                  </li>
                  <li className="flex items-center gap-2">
                    <Check className="w-3.5 h-3.5 text-emerald-400" />
                    <span>Single-tab browser replay</span>
                  </li>
                  <li className="flex items-center gap-2">
                    <Check className="w-3.5 h-3.5 text-emerald-400" />
                    <span>Standard Playwright &amp; Selenium export</span>
                  </li>
                  <li className="flex items-center gap-2">
                    <Check className="w-3.5 h-3.5 text-emerald-400" />
                    <span>Local AES-256 password auto-masking</span>
                  </li>
                </ul>
              </div>

              <a
                href={CHROME_STORE_URL}
                target="_blank"
                rel="noopener noreferrer"
                onClick={() => posthog.capture('clicked_install_chrome_store')}
                className="w-full py-2.5 rounded-lg bg-emerald-500 hover:bg-emerald-400 text-slate-950 text-xs font-mono font-bold text-center transition-all shadow-[0_0_20px_rgba(16,185,129,0.2)] flex items-center justify-center gap-1.5 active:scale-95"
              >
                <span>Add to Chrome — Free</span>
                <ArrowRight className="w-3.5 h-3.5" />
              </a>
            </div>

            {/* Pro Lifetime Tier */}
            <div className="p-7 rounded-xl bg-[#0f172a] border border-emerald-500/40 relative flex flex-col justify-between shadow-[0_0_30px_rgba(16,185,129,0.1)]">
              <div className="absolute -top-3 right-6 px-3 py-0.5 rounded-full bg-emerald-500 text-slate-950 text-[10px] font-mono font-bold uppercase tracking-wider">
                LIFETIME ACCESS
              </div>

              <div>
                <div className="flex items-center justify-between mb-2">
                  <span className="text-xs font-mono text-emerald-400 font-bold uppercase">Pro Lifetime Tier</span>
                </div>
                <div className="flex items-baseline gap-2 mb-4 font-mono">
                  <span className="text-4xl font-extrabold text-white">$29</span>
                  <span className="text-xs text-slate-500 line-through">$79</span>
                  <span className="text-xs text-emerald-400 ml-1">One-time payment</span>
                </div>
                <p className="text-xs text-slate-400 mb-6 leading-relaxed">
                  For engineering teams running automated batch fills and exporting to CI/CD test pipelines.
                </p>

                <ul className="space-y-3 text-xs font-mono text-slate-200 mb-8">
                  <li className="flex items-center gap-2">
                    <Check className="w-3.5 h-3.5 text-emerald-400" />
                    <span><strong>Everything in Community</strong></span>
                  </li>
                  <li className="flex items-center gap-2">
                    <Check className="w-3.5 h-3.5 text-emerald-400" />
                    <span><strong>AES-256 Local Secret Vault</strong></span>
                  </li>
                  <li className="flex items-center gap-2">
                    <Check className="w-3.5 h-3.5 text-emerald-400" />
                    <span><strong>CSV Batch Execution Engine</strong></span>
                  </li>
                  <li className="flex items-center gap-2">
                    <Check className="w-3.5 h-3.5 text-emerald-400" />
                    <span>Multi-format code exporters (Playwright, Puppeteer, Python)</span>
                  </li>
                  <li className="flex items-center gap-2">
                    <Check className="w-3.5 h-3.5 text-emerald-400" />
                    <span>Priority updates &amp; commercial deployment license</span>
                  </li>
                </ul>
              </div>

              <a
                href="https://test.dodopayments.com/buy"
                target="_blank"
                rel="noopener noreferrer"
                onClick={() => posthog.capture('clicked_pro_lifetime_checkout')}
                className="w-full py-2.5 rounded-lg bg-emerald-500 hover:bg-emerald-400 text-slate-950 text-xs font-mono font-bold text-center transition-all shadow-[0_0_20px_rgba(16,185,129,0.3)] block active:scale-95"
              >
                Get Pro Lifetime ($29) — Dodo Payments
              </a>
            </div>
          </div>
        </div>
      </section>

      {/* 6. FOOTER */}
      <footer className="border-t border-slate-800/80 bg-[#090d14] py-10 px-6 text-xs font-mono text-slate-500">
        <div className="max-w-7xl mx-auto flex flex-col sm:flex-row items-center justify-between gap-4">
          <div className="flex items-center gap-2.5 text-slate-400">
            <Image
              src="/flowmacro_store_icon_128x128.png"
              alt="FlowMacro IDE Logo"
              width={20}
              height={20}
              className="rounded"
            />
            <span className="text-white font-bold">FlowMacro IDE</span>
            <span>• Terminal &amp; Security Blueprint Engine</span>
          </div>

          <div className="flex items-center gap-6">
            <Link href="/privacy" className="hover:text-emerald-400 transition-colors">
              Privacy Policy (Zero Data)
            </Link>
            <a
              href="https://github.com"
              target="_blank"
              rel="noopener noreferrer"
              className="hover:text-emerald-400 transition-colors"
            >
              GitHub
            </a>
            <span>Built by Naveen Guru</span>
          </div>
        </div>
      </footer>
    </div>
  );
}
